name: run tasks.py

on:
  schedule:
    # - cron: '*/5 * * * *' # Every 5 minutes
    # - cron: '0 */6 * * *' # Every 6 hours
    # - cron: '5 * * * *' # At minute 5 of every hour 5 + 60*N
    # - cron: '30 20 * * 1-5' # Every weekday (Monday to Friday) at 8:30 PM
    # - cron: '30 9 1 * *' # Every month on the 1st at 9:30 AM
    - cron: '59 23 * * *' # Every day at 11:59 PM
    - cron: '40 09 * * *' # Every day at 9:40 AM
    # - cron: '45 20 * * 5' # At 8:45PM on Friday
    # - cron: '50 20 30 6 *' # June 30th at 8:50 PM
    # - cron: '30 20 31 12 1-5' # December 31st at 8:30 PM ONLY if on weekday

  push:
    branches:
      - main

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run main.py
        env:
          SOME_SECRET: ${{ secrets.API_KEY }}
        run: python tasks.py
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 